# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: docs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Docusaurus_pb2 as Docusaurus__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndocs.proto\x1a\x10\x44ocusaurus.proto\x1a\x1bgoogle/protobuf/empty.proto2J\n\x04\x64ocs\x12\x42\n\x05\x62uild\x12!.sylk.Docusaurus.v1.PresetOptions\x1a\x16.google.protobuf.Emptyb\x06proto3')



_DOCS = DESCRIPTOR.services_by_name['docs']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DOCS._serialized_start=61
  _DOCS._serialized_end=135
# @@protoc_insertion_point(module_scope)
