# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Docusaurus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor

from typing import overload, Iterator, List, Dict
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x44ocusaurus.proto\x12\x12sylk.Docusaurus.v1\"u\n\rPresetOptions\x12/\n\x04sylk\x18\x01 \x01(\x0b\x32!.sylk.Docusaurus.v1.PluginOptions\x12\x33\n\x04\x64ocs\x18\x02 \x01(\x0b\x32%.sylk.Docusaurus.v1.ContentDocOptions\"u\n\rPluginOptions\x12\x15\n\rsylkJsonPaths\x18\x01 \x03(\t\x12\x14\n\x0csylkDocsPath\x18\x02 \x01(\t\x12\x13\n\x0bsidebarPath\x18\x03 \x01(\t\x12\x15\n\rrouteBasePath\x18\x04 \x01(\t\x12\x0b\n\x03git\x18\x05 \x01(\t\"?\n\x11\x43ontentDocOptions\x12\x15\n\rrouteBasePath\x18\x01 \x01(\t\x12\x13\n\x0bsidebarPath\x18\x02 \x01(\tb\x06proto3')



_PRESETOPTIONS = DESCRIPTOR.message_types_by_name['PresetOptions']
_PLUGINOPTIONS = DESCRIPTOR.message_types_by_name['PluginOptions']
_CONTENTDOCOPTIONS = DESCRIPTOR.message_types_by_name['ContentDocOptions']

@overload
class PresetOptions(_message.Message):
	"""sylk.build generated message [sylk.Docusaurus.v1.PresetOptions]
	A class respresent a PresetOptions type
	
	"""
	sylk = PluginOptions # type: PluginOptions
	docs = ContentDocOptions # type: ContentDocOptions

	def __init__(self, sylk=PluginOptions, docs=ContentDocOptions):
		"""
		

		Attributes:
		----------
		sylk : PluginOptions
			
		docs : ContentDocOptions
			
		"""
		pass
PresetOptions = _reflection.GeneratedProtocolMessageType('PresetOptions', (_message.Message,), {
  'DESCRIPTOR' : _PRESETOPTIONS,
  '__module__' : 'Docusaurus_pb2'
  # @@protoc_insertion_point(class_scope:sylk.Docusaurus.v1.PresetOptions)
  })
_sym_db.RegisterMessage(PresetOptions)


@overload
class PluginOptions(_message.Message):
	"""sylk.build generated message [sylk.Docusaurus.v1.PluginOptions]
	A class respresent a PluginOptions type
	
	"""
	sylkJsonPaths = List[str] # type: List[str]
	sylkDocsPath = str # type: str
	sidebarPath = str # type: str
	routeBasePath = str # type: str
	git = str # type: str

	def __init__(self, sylkJsonPaths=List[str], sylkDocsPath=str, sidebarPath=str, routeBasePath=str, git=str):
		"""
		

		Attributes:
		----------
		sylkJsonPaths : List[str]
			
		sylkDocsPath : str
			
		sidebarPath : str
			
		routeBasePath : str
			
		git : str
			
		"""
		pass
PluginOptions = _reflection.GeneratedProtocolMessageType('PluginOptions', (_message.Message,), {
  'DESCRIPTOR' : _PLUGINOPTIONS,
  '__module__' : 'Docusaurus_pb2'
  # @@protoc_insertion_point(class_scope:sylk.Docusaurus.v1.PluginOptions)
  })
_sym_db.RegisterMessage(PluginOptions)


@overload
class ContentDocOptions(_message.Message):
	"""sylk.build generated message [sylk.Docusaurus.v1.ContentDocOptions]
	A class respresent a ContentDocOptions type
	
	"""
	routeBasePath = str # type: str
	sidebarPath = str # type: str

	def __init__(self, routeBasePath=str, sidebarPath=str):
		"""
		

		Attributes:
		----------
		routeBasePath : str
			
		sidebarPath : str
			
		"""
		pass
ContentDocOptions = _reflection.GeneratedProtocolMessageType('ContentDocOptions', (_message.Message,), {
  'DESCRIPTOR' : _CONTENTDOCOPTIONS,
  '__module__' : 'Docusaurus_pb2'
  # @@protoc_insertion_point(class_scope:sylk.Docusaurus.v1.ContentDocOptions)
  })
_sym_db.RegisterMessage(ContentDocOptions)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRESETOPTIONS._serialized_start=40
  _PRESETOPTIONS._serialized_end=157
  _PLUGINOPTIONS._serialized_start=159
  _PLUGINOPTIONS._serialized_end=276
  _CONTENTDOCOPTIONS._serialized_start=278
  _CONTENTDOCOPTIONS._serialized_end=341
# @@protoc_insertion_point(module_scope)
