# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Docusaurus_pb2 as Docusaurus__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class docsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.build = channel.unary_unary(
                '/docs/build',
                request_serializer=Docusaurus__pb2.PresetOptions.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class docsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def build(self, request, context):
        """[sylk] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_docsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'build': grpc.unary_unary_rpc_method_handler(
                    servicer.build,
                    request_deserializer=Docusaurus__pb2.PresetOptions.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'docs', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class docs(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def build(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/docs/build',
            Docusaurus__pb2.PresetOptions.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
